name: Lint & build
on:
  push:
    branch: master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Setup dependency caching
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Mock env
        run: |
          echo -e "SECRET_KEY=" \
            "\nPUBLIC_PACKETA_APIKEY=" \
            "\nGITHUB_CLIENT_ID=" \
            "\nGITHUB_CLIENT_SECRET=" \
            "\nAUTHORIZED_USERS_GITHUB_IDS=" \
            "\nDATABASE_URL=" > .env

      - name: Build (to get generated types)
        run: yarn run build

      - name: Lint
        run: yarn run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/mvolfik/arleto-cz:latest
